name: ci-verify

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run iSort
        shell: bash -l {0}
        run: isort --diff .

      - name: Run Black
        shell: bash -l {0}
        run: black --check .

      - name: Run MyPy
        shell: bash -l {0}
        run: mypy

      - name: PyTest
        shell: bash -l {0}
        run: pytest